### PR TITLE
Feature/search bar

### PR DESCRIPTION
**Pull request by vivi7**
🚀 A search bar appears on the top of the menu, on enter it filter the results
(>= macOS 10.11)

### CODE REVIEW

**Comment by Econa77** [comment]
@vivi7 Thank you for your nice PR.

I'm sorry, the search function is trying to proceed with implementation separating from existing menus. I'm thankful for making PR, but I will implement other search function at the next release. So I closed PR.

Thank you for the contribution 👍

**Comment by vivi7** [comment]
@Econa77 No problem, I didn't know about the app flow features, and I also did this searchbar because I needed, but I know that was not in the best pratices style, but I decided anyway to create the pr because I aspected someone that wants to implement it and I'm ready if you need help.

**Comment by amarendra** [comment]
Hi @Econa77, is there any beta release of Clipy with search functionality?
I notice there was a release (Nov 17) after your comment (Apr 17) but I could not find the search functionality in that. So will it coming in next release by any chance?

**Comment by ghost** [comment]
Hey @Econa77, is there any news about this functionality? thanks

**Comment by Lzyct** [comment]
still no feature search history clipboard ? thanks

**Comment by ilaigold** [comment]
Still waiting :)

**Pull request closed without merging**
