### PR TITLE
Feature/multi snippet managment

### PR DESCRIPTION
**Pull request by vivi7**
:rocket: Added multi management for snippets

### CODE REVIEW

**Comment by Econa77** [comment]
@vivi7 Thank you for your great PR.

This PR implements two functions. Please will it separate the PR for each function?
- Add multi snippet management
- Add import/export .json file

**Comment by Econa77** [comment]
@vivi7 And why did you try to add the export .json file? Did not you just use xml?

**Comment by vivi7** [comment]
@Econa77 I'm so sorry I was with the github push notification turned off so I didin't see your comment, I'm really sorry, Infact I aspected some comments and I was stranged that I never had an answer, I'm really sorry again, I will be activier on the project.

**Comment by vivi7** [comment]
for the two function PR, I'm going to create them as soon as possible

**Comment by vivi7** [comment]
The reason for the json was because it's simpler to read when you open the file with a normal text editor. and the implementation was simple

**Pull request closed without merging**
